
# MongoDb, Delete a Document or deleteOne() , showing {acknowledged: true, deletedCount: 0}, but _Id is ok

**when trying to delete one items from the Database , It's not deleting but the acknowledgement showing true, deletedCount:0 , and nothing is deleting from the database. **
```**
**
# Here this is my code of Client Side**
`

const client = new MongoClient(uri, { useNewUrlParser: true, useUnifiedTopology: true, serverApi: ServerApiVersion.v1 });
const run = async()=> {
try{
const productCollection =client.db('productCMS').collection("AllProducts")


// Read One 
app.get('/products/:id', async(req, res) => {
    const id= req.params.id
    const query ={_id: ObjectId(id)}
    const result= await productCollection.findOne(query)
    console.log(result)
    res.send(result)
})



// Read All
app.get('/products',  async(req, res) => {
    const query ={}
    const cursor=productCollection.find(query)
    const result= await cursor.toArray()
    console.log(result)
    res.send(result)
})




// write
app.post('/products', async(req, res) => {
    const products= req.body
    const result= await productCollection.insertOne(products)
    console.log(result)
    res.send(result)


})


// DELETE 
app.delete('/products/:id', async(req, res)=> {
    const id = req.params._id
    console.log(id)
    const query= {_id: ObjectId(id)}
    const result= await productCollection.deleteOne(query)
    console.log(result)
    res.send(result)
})

}
finally {
}
}
run().catch(err=>console.log(err))
app.get('/' , (req, res)=> {
res.send('The sever is Running....')
})
app.listen(port, ()=> {
console.log('Server Port', port)
})
`


        