
# Does run_coroutine_threadsafe only hold a weak reference to its task?

The current docs for asyncio.create_task say:

Important: Save a reference to the result of this function, to avoid a task disappearing mid-execution. The event loop only keeps weak references to tasks.

The docs for asyncio.run_coroutine_threadsafe do not have this warning. However, looking at the code, I can't see a (non-cyclic) strong reference being made once create_task has been invoked on the event loop. Are the docs just missing this? Do I risk my coroutine not running if I do not keep a strong reference to the future returned by run_coroutine_threadsafe? If not, where is the strong reference being kept?
(I have tried to force the task to be freed by calling gc.collect() but for some reason I can't even reproduce the known problem with create_task, let alone test whether run_coroutine_threadsafe has the same issue.)

        