
# Getting 401 from Solace API when giving access

I'm trying to connect to Solace using the Solace Node.JS API. I'm connecting with the client credentials workflow. I'm passing in the access token returned from the authorization URL in the form of a JWT. That is:
sessionParameters.accessToken = <mythree.part.jwttoken>
sessionParameters.authenticationScheme= 'AuthenticationScheme_oauth2'

The session object gets created. In the past, I passed in the wrong session parameters and it failed at the
solace.SolclientFactory.createSession() 

call. Now, I get a session object. However, the
solace.SessionEventCode.CONNECT_FAILED_ERROR handler gets called with
{
  "name": "OperationError",
  "subcode": 13,
  "_reason": {
    "_transportEventCode": 2,
    "_infoStr": "Disconnecting session",
    "_responseCode": null,
    "_errorSubcode": 0,
    "_sid": 1667316586668
  },
  "_sessionEventCode": 2,
  "_infoStr": "Unauthorized",
  "_responseCode": 401,
  "_errorSubcode": 13
}


What should I look for?

        