
# `SynchronousOnlyOperation` error while trying to run Playwright automation triggered django admin action

This is the error:
SynchronousOnlyOperation at /admin/app/modelA/
You cannot call this from an async context - use a thread or sync_to_async.

What I'm trying to do is:
I have an action in django-admin that intends to run an automated task with Playwright.
The action in admin.py looks like this:
@admin.action(description="Do task")
def run_task(modeladmin, request, queryset):
    for obj in queryset:
        task = Task(obj)
        task.run()

And the Task class looks like this:
class Task:
    def __init__(self, task: Task) -> None:
        self.task = task

    def run(self):
        with sync_playwright() as p:
            browser = p.chromium.launch(headless=True)
            page = browser.new_page()

            page.go_to("www.google.com")
            # DO SOME STUFF

            browser.close()
    

And when I run the action the error shows as soon as chromium gets ready.
Thank you beforehand.

I expect it to do the stuff without running at least get the title of the page.
I tried using sync_to_async as these docs suggest, implemented it in two ways (which I believe are wrong)
First way I tried:
Is by trying to use sync async in the admin.py file when the function Task.run is called:
@admin.action(description="Do task")
def run_test(modeladmin, request, queryset):
    for obj in queryset:
        task = Task(obj)
        sync_to_async(task.run, thread_sensitive=True)

It didn't work
2. Second way I tried:
Is by adding the decorator as well to the run function
...
    @sync_to_async
    def run(self, ...):
        ...
...

It didn't work

Full traceback:
Environment:


Request Method: POST
Request URL: http://0.0.0.0:8000/admin/app/task/

Django Version: 4.1.3
Python Version: 3.10.5
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'app.apps.AppConfig',
 'nested_admin']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware']



Traceback (most recent call last):
  File ".../venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File ".../venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File ".../venv/lib/python3.10/site-packages/django/contrib/admin/options.py", line 686, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File ".../venv/lib/python3.10/site-packages/django/utils/decorators.py", line 133, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File ".../venv/lib/python3.10/site-packages/django/views/decorators/cache.py", line 62, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File ".../venv/lib/python3.10/site-packages/django/contrib/admin/sites.py", line 242, in inner
    return view(request, *args, **kwargs)
  File ".../venv/lib/python3.10/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File ".../venv/lib/python3.10/site-packages/django/utils/decorators.py", line 133, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File ".../venv/lib/python3.10/site-packages/django/contrib/admin/options.py", line 1964, in changelist_view
    response = self.response_action(
  File ".../venv/lib/python3.10/site-packages/django/contrib/admin/options.py", line 1593, in response_action
    response = func(self, request, queryset)
  File ".../app/admin.py", line 13, in run_test
    task.run()
  File ".../app/tasks.py", line 14, in run
    for step in self.steps:
  File ".../venv/lib/python3.10/site-packages/django/db/models/query.py", line 394, in __iter__
    self._fetch_all()
  File ".../venv/lib/python3.10/site-packages/django/db/models/query.py", line 1866, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File ".../venv/lib/python3.10/site-packages/django/db/models/query.py", line 87, in __iter__
    results = compiler.execute_sql(
  File ".../venv/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1396, in execute_sql
    cursor = self.connection.cursor()
  File ".../venv/lib/python3.10/site-packages/django/utils/asyncio.py", line 24, in inner
    raise SynchronousOnlyOperation(message)

Exception Type: SynchronousOnlyOperation at /admin/app/task/
Exception Value: You cannot call this from an async context - use a thread or sync_to_async.


        