
# python call-back for python module segments

I am writing a python module for using a c++ lib, which uses call-backs. (asyn calls)
1: passing python function as below
Py_XINCREF(cb_p);
if(!PyArg_ParseTuple(args, "ky#O",
  316                         &hdl,
  317                         &(buf_p), &(buflen),
  318                         &(cb_p->ctrl_cb))) {
;
;
;
Py_XINCREF(cb_p->ctrl_cb);

PyCallable_Check passes. able to call the call-back.
This call-back PyObject * set in cb_p which is in heap, and refcounted (both cb_p, cb_p->ctrl_cb) (Py_XINCREF)
2: when the c++ call-back is called,

cb_p is fetched
cb_p->ctrl_cb is called using PyEval_CallObject(cb_p->ctrl_cb, arglist);

  274   arglist = Py_BuildValue("(y#, i)",
  275                           (const char *)(ack_p->ctrl_msg_p->ep_id.key),
  276                           (Py_ssize_t)ack_p->ctrl_msg_p->ep_id.klen,
  277                           status);
  278
~ 279   if (!PyCallable_Check(cb_p->ctrl_cb)) {
+ 280     PyErr_SetString(PyExc_TypeError, "callback invalid");
+ 281     return;
+ 282   }
+ 283   PyEval_CallObject(cb_p->ctrl_cb, arglist);
+ 284   Py_DECREF(arglist);

When doing so, is get a core
(gdb) bt
#0  0x00000000005da418 in _PyFunction_FastCallDict ()
#1  0x00007ffff76fe53b in s_mpsc_pub_ctrl_cb (ack_p=<optimized out>) at py_mpsc.c:290
#2  0x00007ffff76c740c in s_mpsc_ctrl_msg_ack_recv (mpsc_p=0x9a9e00, buf=buf@entry=0x7fffb8003997 "\n\017/python/app/pub\020\001", len=len@entry=19, sequence=sequence@entry=0) at ./infra/pubsub/mpsc/mpsc_conn.cpp:1392
#3  0x00007ffff76c7cb2 in mpsc_ctrl_recv_obj_cookie (p_h=0x7fffc0005aa0, op=<optimized out>, msgtype=73006, buf=0x7fffb8003997 "\n\017/python/app/pub\020\001", len=19, sequence=0) at ./infra/pubsub/mpsc/mpsc_conn.cpp:1476
#4  0x00007ffff7297b4a in do_recv (ctx=<optimized out>, arg=<optimized out>, fsm_hdl=<optimized out>) at ./infra/msglib/lib/ml_peer_server.c:312
#5  0x00007ffff7297a69 in fsm_execute (f=0x7fffc0005a20, event=event@entry=1, arg=<optimized out>) at ./infra/msglib/lib/fsm.c:74
#6  0x00007ffff729acd3 in ml_peer_event (p=p@entry=0x7fffc0005aa0, ev=ev@entry=1, arg=<optimized out>) at ./infra/msglib/lib/ml_peer.c:116
#7  0x00007ffff729aee9 in ml_peer_signal_recv (p=p@entry=0x7fffc0005aa0, m=<optimized out>) at ./infra/msglib/lib/ml_peer.c:178
#8  0x00007ffff729d037 in input_recv (c=<optimized out>, msg=0x7fffc0000b68) at ./infra/msglib/lib/ml_client.c:30
#9  0x00007ffff72959a1 in read_cb (fd=<optimized out>, what=<optimized out>, _self=0x7fffc0000b40) at ./infra/msglib/lib/ml_cmn.c:234
#10 0x00007ffff74159ba in ?? () from /lib/x86_64-linux-gnu/libevent-2.1.so.6
#11 0x00007ffff7416537 in event_base_loop () from /lib/x86_64-linux-gnu/libevent-2.1.so.6
#12 0x00007ffff7656404 in s_dispatcher (in=<optimized out>) at ./infra/pubsub/common/tepool/tepool.cpp:182
#13 0x00007ffff7f72fa3 in start_thread (arg=<optimized out>) at pthread_create.c:486
#14 0x00007ffff7cba06f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
(gdb)

I only the get the core when the main python is
while True:
    time.sleep(100)


instead of sleep if i do
while True:
    pass


no core, everything works as expected.
I think somewhere I need to make sure the python function object need to ref-counted, I was hoping
Py_XINCREF(cb_p->ctrl_cb) does that. any help to gain some insight here is appreciated.

        