
# Mypy error when a python file has the same name as a directory

Here is a simple reproducible example:
Architecture of the files:

__init__.py is empty.
my_folder.py is empty.
In test_file.py there is:
from my_aux_file import main

def test_main() -> None:
    main()

In my_aux_file.py, there is:
def main():
    print("Hello")

Running pytest --mypy in the terminal will output this:
PS C:\Users\lhott\Desktop\pytest_bug> pytest --mypy
=================================================================== test session starts ===================================================================
platform win32 -- Python 3.11.0, pytest-7.2.0, pluggy-1.0.0
rootdir: C:\Users\lhott\Desktop\pytest_bug
plugins: mypy-0.10.0
collected 6 items

my_aux_file.py .F                                                                                                                                    [ 33%]
my_folder.py .                                                                                                                                       [ 50%]
my_folder\__init__.py F                                                                                                                              [ 66%]
my_folder\test_file.py ..                                                                                                                            [100%]

======================================================================== FAILURES =========================================================================
______________________________________________________________________ test session _______________________________________________________________________
mypy exited with status 2.
__________________________________________________________________ my_folder\__init__.py __________________________________________________________________
 error: Duplicate module named "my_folder" (also at "C:\Users\lhott\Desktop\pytest_bug\my_folder.py")
 note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#mapping-file-paths-to-modules for more info
 note: Common resolutions include: a) using `--exclude` to avoid checking one of them, b) adding `__init__.py` somewhere, c) using `--explicit-package-bases` or adjusting MYPYPATH
==================================================================== warnings summary =====================================================================
my_aux_file.py::mypy
  C:\Users\lhott\AppData\Local\Programs\Python\Python311\Lib\site-packages\mypy\util.py:28: DeprecationWarning: path is deprecated. Use files() instead. Refer to https://importlib-resources.readthedocs.io/en/latest/using.html#migrating-from-legacy for migration advice.
    with importlib_resources.path(

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
========================================================================== mypy ===========================================================================
Found 1 error in 1 file (errors prevented further checking)
================================================================= short test summary info =================================================================
FAILED my_aux_file.py::mypy-status
FAILED my_folder/__init__.py::mypy
========================================================= 2 failed, 4 passed, 1 warning in 0.10s ==========================================================

Why am I not allowed to have a python module named the same as a subpackage?

        