
# Explode() function is leading to cannot handle a non-unique multi-index! error

I have a dataframe with columns which has list values:
df = pd.DataFrame({'var1': ['[2.0, 2.0, 2.0, 2.0]', '[1.0, 5.0]', '[2.0, 2.0, 2.0, 2.0]', '[6.0]', '[2.0, 5.0]', '[2.0, 2.0, 2.0, 2.0]', '[3.0]', '[1.0, 5.0]'], 
                   'var2': ['[A4003250601, A4003250601, A4003250601, A4003250601]','[A4002000401, A9262000201]', '[A4003250601, A4003250601, A4003250601, A4003250601]', '[A4001800801]', '[A4002000401, A9262000201]', '[A4003250601, A4003250601, A4003250601, A4003250601]', '[A4001800801]', '[A4002000401, A9262000201]'], 
                   'var3': ['[335.764, 335.764, 335.764, 335.764]', '[191.0, 310.0]', '[335.764, 335.764, 335.764, 335.764]', '[240.0]', '[191.0, 310.0]', '[335.764, 335.764, 335.764, 335.764]', '[240.0]', '[191.0, 310.0]'], 
                   'var4':['[15659839, 15659839, 15659839, 15659839]', '[15659891, 15659891]', '[15659839, 15659839, 15659839, 15659839]', '[15659891]', '[15659891, 15659891]', '[15659839, 15659839, 15659839, 15659839]', '[15659891]', '[15659891, 15659891]'], 
                   'var5':['[PMAC, PMAC, PMAC, PMAC]', '[SUNDARAM FASTENERS LTD (GUMMIDIPOONDI), AUTOLEC DIVISION , SUNDARAM FASTENERS LTD (GUMMIDIPOONDI), AUTOLEC DIVISION ]', '[PMAC, PMAC, PMAC, PMAC]', '[SUNDARAM FASTENERS LTD (GUMMIDIPOONDI), AUTOLEC DIVISION ]', '[SUNDARAM FASTENERS LTD (GUMMIDIPOONDI), AUTOLEC DIVISION , SUNDARAM FASTENERS LTD (GUMMIDIPOONDI), AUTOLEC DIVISION ]', '[PMAC, PMAC, PMAC, PMAC]', '[SUNDARAM FASTENERS LTD (GUMMIDIPOONDI), AUTOLEC DIVISION ]', '[SUNDARAM FASTENERS LTD (GUMMIDIPOONDI), AUTOLEC DIVISION , SUNDARAM FASTENERS LTD (GUMMIDIPOONDI), AUTOLEC DIVISION ]'],
                   'var6': [20221031,20221031,20221101, 20221101, 20221101, 20221102,20221102,20221102],
                   'var7':[0.8544,0.42, 0.8544, 0.729,0.42, 0.8544, 0.729, 0.42],
                   'var8':[1200,1000,1200,900,1000,1200,900,1000]})

While trying to get the list elements in a separate rows, I am getting error as ValueError: cannot handle a non-unique multi-index!
The code I am using:
(df.set_index(['var6', 'var7', 'var8']) 
       .apply(lambda col: col.astype(str).str.split(',')
       .explode())
       .reset_index()
       .reindex(df.columns, axis=1))

Note: I have checked and the code works fine prior to explode. But once explode() is used the error pops up.

        